[package]
name = "cell"
version = "0.1.0"
edition = "2024"

[features]
auto-egui = []
dbg-schedules = ["auto-egui"]

[dependencies]
anarchy = { path = "../anarchy" }
mutual = "1.0.2"
magician-vgpu = { path = "../shader_magician/magician-vgpu" }

winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.11"
pollster = "0.4"
derive_more = "2.1.1"

egui = "0.34"
egui-wgpu = "0.34"
egui-winit = { version = "0.34", default-features = false }
chrono = "0.4.45"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui-winit = { version = "0.34", default-features = false, features = ["clipboard", "links", "wayland", "x11"] }
wgpu = "29.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
egui-winit = { version = "0.34", default-features = false, features = ["links"] }
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "29.0", features = ["webgl"]}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}
log = "0.4.33"
